-- Activities table
CREATE TABLE ACTIVITY (
		ID UUID NOT NULL,
		END_TIME TIMESTAMP,
		ADJUSTED BOOLEAN,
		START_TIME TIMESTAMP,
		SUMMARY VARCHAR(1024),
		TASK_ID VARCHAR(512),
		REPOSITORY_URL VARCHAR(512)
	);

-- Relation table between tracked tasks and activities
CREATE TABLE TRACKEDTASK_ACTIVITY (
		TASK_ID VARCHAR(512) NOT NULL,
		REPOSITORY_URL VARCHAR(512) NOT NULL,
		ACTIVITIES_ID UUID NOT NULL
	);

-- Tracked task table
CREATE TABLE TRACKEDTASK (
		TASK_ID VARCHAR(512) NOT NULL,
		REPOSITORY_URL VARCHAR(512) NOT NULL,
		TICK TIMESTAMP,
		CURRENTACTIVITY_ID UUID
	);

CREATE INDEX FK_TRACKEDTASK_CURRENTACTIVITY_ID_INDEX_E ON TRACKEDTASK (CURRENTACTIVITY_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C ON ACTIVITY (ID ASC);

CREATE INDEX FK_TRACKEDTASK_ACTIVITY_ACTIVITIES_ID_INDEX_1 ON TRACKEDTASK_ACTIVITY (ACTIVITIES_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_1 ON TRACKEDTASK_ACTIVITY (TASK_ID ASC, REPOSITORY_URL ASC, ACTIVITIES_ID ASC);

CREATE INDEX FK_ACTIVITY_TASK_ID_INDEX_C ON ACTIVITY (TASK_ID ASC, REPOSITORY_URL ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_E ON TRACKEDTASK (TASK_ID ASC, REPOSITORY_URL ASC);

ALTER TABLE TRACKEDTASK_ACTIVITY ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY (TASK_ID, REPOSITORY_URL, ACTIVITIES_ID);

ALTER TABLE TRACKEDTASK ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY (TASK_ID, REPOSITORY_URL);

ALTER TABLE ACTIVITY ADD CONSTRAINT PRIMARY_KEY_C UNIQUE (ID);

ALTER TABLE ACTIVITY ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID);

ALTER TABLE TRACKEDTASK ADD CONSTRAINT PRIMARY_KEY_E UNIQUE (TASK_ID, REPOSITORY_URL);

ALTER TABLE TRACKEDTASK_ACTIVITY ADD CONSTRAINT FK_TRACKEDTASK_ACTIVITY_ACTIVITIES_ID FOREIGN KEY (ACTIVITIES_ID)
	REFERENCES ACTIVITY (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE TRACKEDTASK ADD CONSTRAINT FK_TRACKEDTASK_CURRENTACTIVITY_ID FOREIGN KEY (CURRENTACTIVITY_ID)
	REFERENCES ACTIVITY (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE TRACKEDTASK_ACTIVITY ADD CONSTRAINT FK_TRACKEDTASK_ACTIVITY_TASK_ID FOREIGN KEY (TASK_ID, REPOSITORY_URL)
	REFERENCES TRACKEDTASK (TASK_ID, REPOSITORY_URL)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_TASK_ID FOREIGN KEY (TASK_ID, REPOSITORY_URL)
	REFERENCES TRACKEDTASK (TASK_ID, REPOSITORY_URL)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

